"""add model_name to document chunk embeddings

Revision ID: 781930ff9eca
Revises: a6904d990316
Create Date: 2026-08-03 07:27:44.748783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '781930ff9eca'
down_revision: Union[str, Sequence[str], None] = 'a6904d990316'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "document_chunk_embeddings",
        sa.Column(
            "model_name",
            sa.String(length=100),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_chunk_embeddings', 'model_name')
    # ### end Alembic commands ###
